name: 'Npm security audit'
description: 'Checks if project dependencies have any known vulnerabilities.'
inputs:
  project-path:
    default: .
    description: NPM project localization
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-path }}
