name: Check npm dependency duplications

on:
  workflow_call:

jobs:
  check_duplications:
    name: Check dependency duplications
    runs-on: ubuntu-latest
    steps:
      - run: |
          npm dedupe
          git status -s | grep " M package-lock.json" && echo "::"warning file=package-lock.json"::"Duplicate dependencies found. Run npm dedupe to remove them, or add --dry-run parameter to get more info.
          git reset --hard HEAD
