name: Check npm dependency duplications

on:
  workflow_call:
    inputs:
      node-version:
        default: 16
        description: Node version passed to the actions/setup-node
        required: false
        type: string
      cache:
        default: npm
        description: Package manager for caching - passed to the actions/setup-node
        required: false
        type: string
      project-path:
        default: .
        description: NPM project localization
        required: false
        type: string

jobs:
  check_duplications:
    name: Check dependency duplications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          cache: ${{ inputs.cache }}
          node-version: ${{ inputs.node-version }}
      - name: Check duplications
        run: |
          cd ${{ inputs.project-path }}
          npm dedupe
          git status -s | grep " M package-lock.json" && echo "::"warning file=package-lock.json"::"Duplicate dependencies found. Run npm dedupe to remove them, or add --dry-run parameter to get more info.
          git reset --hard HEAD
