name: Check npm dependency vulnerabilities

on:
  workflow_call:

jobs:
  check_duplications:
    name: Check dependency vulnerabilities
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Use Node.js 16
        uses: actions/setup-node@v2.5.0
        with:
          cache: npm
          node-version: 16
      - run: |
          npm audit fix || true # skip non-0 exit
          git status -s | grep " M package-lock.json" && echo "::"warning file=package-lock.json"::"Found vulnerabilities in the project dependencies. Run npm audit to show the audit details. More info: https://docs.npmjs.com/cli/v7/commands/npm-audit
          git reset --hard HEAD
