name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test dedupe
        run: ./actions/npm-dependency-duplications/runTests.sh
